### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by thakaj** [learn-co-curriculum/phase-0-macos-env-introduction#1]
You may have heard of other UNIX-based operating systems like Ubuntu, Debian, or Fedora, which share a which include the Linux kernel (core software). These types of operating systems work similarly.

->"which share a which include the"

Just thought this was incorrect

**Comment by lizbur10** [comment]
Hi there! Thank you for spotting this issue and providing feedback. The lesson has been updated to fix the error.

Thanks for contributing to the Flatiron School curriculum! 💙
