### ISSUE TITLE
impact of using smart and user-friendly command line shell for macOS , such as fish

### ISSUE THREAD

**Issue by Arimoro2020** [learn-co-curriculum/phase-0-macos-env-introduction#6]
### Canvas Link

https://learning.flatironschool.com/courses/6611/pages/introduction-to-macos-environment-setup?module_item_id=525424

### Concern

Not in README!

### Additional Context

I'd like to know if you'll recommend installing an innovative and user-friendly command line shell for macOS, such as fish., or uninstalling it if someone has it in their MacBook terminal already.

**Comment by lizbur10** [comment]
Hi @Arimoro2020 ! Our official recommendation is to use `zsh`, to ensure that instructions in the curriculum match what students see in their terminal. You are, of course, free to use another shell if you prefer, but just keep in mind that you may encounter some inconsistencies. 

If someone already has another shell program installed, they can always try it and see if they run into problems. If so, they can always install `zsh` later.

Hope this helps 💙
